"""Distractors for Aerodynamics cards (aer-1 ... aer-58)."""

AER = {
    # aer-1: In stable glide, which force opposes the total weight?
    "aer-1": [
        "Lift alone (the vertical component of the aerodynamic force).",
        "Drag alone (the horizontal component of the aerodynamic force).",
        "The induced thrust generated by the wing's forward motion.",
    ],
    # aer-2: Aspect ratio is the ratio between?
    "aer-2": [
        "…wing area and total flight weight.",
        "…wingspan and total wing area.",
        "…mean chord and wingspan squared.",
    ],
    # aer-3: Wings with high aspect ratio have?
    "aer-3": [
        "…small span and large mean chord.",
        "…large span and large mean chord.",
        "…small span and small mean chord.",
    ],
    # aer-4: Quadrupled airflow speed — drag?
    "aer-4": [
        "…drag increases 4× (drag is proportional to velocity).",
        "…drag increases 8× (drag is proportional to velocity cubed).",
        "…drag increases 2× (drag is proportional to the square root of velocity).",
    ],
    # aer-5: Body moves away from Earth's surface — drag?
    "aer-5": [
        "…its drag increases (lower temperature increases air viscosity).",
        "…its drag remains unchanged (drag depends only on shape and speed).",
        "…its drag decreases only above 5500 m, where density halves.",
    ],
    # aer-6: Motion around longitudinal axis is called?
    "aer-6": [
        "…pitch (nicken).",
        "…yaw (gieren).",
        "…trim.",
    ],
    # aer-7: Formula for aspect ratio?
    "aer-7": [
        "Aspect ratio = span × mean chord.",
        "Aspect ratio = mean chord ÷ span.",
        "Aspect ratio = wing area ÷ span².",
    ],
    # aer-8: At 1100 m AMSL, drag is?
    "aer-8": [
        "…about 64% of the drag at sea level.",
        "…about 72% of the drag at sea level.",
        "…about 100% of the drag at sea level (no change up to FL100).",
    ],
    # aer-9: How is wing loading calculated?
    "aer-9": [
        "Wing area ÷ total flight weight.",
        "Total flight weight × wing area.",
        "Pilot weight only ÷ wing area.",
    ],
    # aer-10: Polar curve name?
    "aer-10": [
        "The glide diagram (Gleitdiagramm).",
        "The lift envelope (Auftriebskurve).",
        "The performance polar (Leistungsdiagramm).",
    ],
    # aer-11: At 4400 m AMSL, drag is?
    "aer-11": [
        "…about 90%.",
        "…about 50%.",
        "…about 81%.",
    ],
    # aer-12: Separation point means?
    "aer-12": [
        "The point where lift is maximum on the wing.",
        "The point where the lines attach to the wing.",
        "The point of greatest internal pressure inside the wing.",
    ],
    # aer-13: Body rises — drag decreases…?
    "aer-13": [
        "…linearly with altitude — the rate of decrease is constant from ground to tropopause.",
        "…slower in the lower atmosphere and faster at higher altitudes (density drops more sharply with height).",
        "…in steps at each kilometre boundary, with no change in between.",
    ],
    # aer-14: Increased drag on a glider — effect?
    "aer-14": [
        "…the glide angle becomes shallower (better glide ratio).",
        "…the glide angle remains the same; only flight speed changes.",
        "…the wing area increases proportionally to compensate.",
    ],
    # aer-15: At minimum payload, glider stalls at?
    "aer-15": [
        "…a HIGHER speed than at maximum payload.",
        "…the same speed as at maximum payload (stall is independent of weight).",
        "…the same speed but with a different angle of attack.",
    ],
    # aer-16: Whether a wing generates lift depends primarily on?
    "aer-16": [
        "…wing area.",
        "…air density.",
        "…wing loading.",
    ],
    # aer-17: Mean chord of wing 10 m span, 12.5 m² area?
    "aer-17": [
        "0.8 m (10 ÷ 12.5).",
        "2.5 m (12.5 ÷ 5).",
        "8 m (10 − 12.5 ÷ 2 negative scale).",
    ],
    # aer-18: Glider yawing on its own — what's missing?
    "aer-18": [
        "…pitch stable (Nickstabil).",
        "…roll stable (Rollstabil).",
        "…laterally trimmed.",
    ],
    # aer-19: 4 factors lift depends on?
    "aer-19": [
        "1. Pilot weight\n2. Reserve weight\n3. Air pressure\n4. Air temperature\n\nFormula: L = m × g × p × T",
        "1. Wing loading\n2. Aspect ratio\n3. Air humidity\n4. Glide angle\n\nFormula: L = W × AR × h × α",
        "1. Wingspan\n2. Mean chord\n3. Drag coefficient\n4. Cell pressure\n\nFormula: L = b × c × CD × P",
    ],
    # aer-20: Wing loading is?
    "aer-20": [
        "…the ratio of pilot weight to wing area (excluding harness and equipment).",
        "…the ratio of wing area to total flight weight.",
        "…the ratio of payload to maximum certified weight.",
    ],
    # aer-21: 54 km/h (15 m/s), 2 m/s sink, 18 km/h (5 m/s) headwind — glide over ground?
    "aer-21": [
        "Ground speed = 15 + 5 = 20 m/s. Glide = 20 ÷ 2 = 10.",
        "Ground speed = 15 − 5 = 10 m/s. Glide = 2 ÷ 10 = 0.2.",
        "Ground speed = 54 − 18 = 36 km/h. Glide = 36 ÷ 2 = 18.",
    ],
    # aer-22: Halved air density — drag?
    "aer-22": [
        "…drag also quadruples.",
        "…drag stays the same.",
        "…drag is reduced to one quarter.",
    ],
    # aer-23: Resultant aerodynamic force in trim vs full-accelerated flight?
    "aer-23": [
        "…is much larger in fast flight, because the wing must support more centrifugal load.",
        "…is smaller in fast flight, because the wing is more efficient at speed.",
        "…drops to zero in fully accelerated flight.",
    ],
    # aer-24: Force perpendicular to lift?
    "aer-24": [
        "Weight.",
        "Total aerodynamic force.",
        "Centrifugal force.",
    ],
    # aer-25: 100 kg total, 250 kg in turn — load factor?
    "aer-25": [
        "1.5 g.",
        "3.5 g.",
        "150 kg.",
    ],
    # aer-26: At best-glide speed, +2° AoA?
    "aer-26": [
        "…decreases the lift coefficient.",
        "…increases the drag coefficient only; lift stays the same.",
        "…has no effect on either coefficient if airspeed is unchanged.",
    ],
    # aer-27: Lift distribution at +10° AoA?
    "aer-27": [
        "1/3 from the upper surface (suction) and 2/3 from the lower surface (pressure).",
        "1/2 from each surface — lift is always equally distributed.",
        "All lift comes from the upper surface; the lower surface only contributes drag.",
    ],
    # aer-28: At 3300 m AMSL, drag is?
    "aer-28": [
        "…about 90%.",
        "…about 81%.",
        "…about 50%.",
    ],
    # aer-29: Glider that continuously speeds up by itself?
    "aer-29": [
        "…stable flight characteristics.",
        "…neutrally stable (indifferent) flight characteristics.",
        "…directionally unstable but pitch-stable characteristics.",
    ],
    # aer-30: Drag depends on (1)?
    "aer-30": [
        "The weight of the body.",
        "The molecular structure of the material.",
        "The humidity of the surrounding air.",
    ],
    # aer-31: Drag depends on (2)?
    "aer-31": [
        "The mass of the body.",
        "The colour and surface texture of the body.",
        "The temperature of the body.",
    ],
    # aer-32: Drag depends on (3)?
    "aer-32": [
        "Air humidity.",
        "Atmospheric pressure gradient.",
        "Dew point of the surrounding air.",
    ],
    # aer-33: Wings with low aspect ratio have?
    "aer-33": [
        "…large span and small mean chord.",
        "…small span and small mean chord.",
        "…large span and large mean chord.",
    ],
    # aer-34: Where are vortices found around a flying glider?
    "aer-34": [
        "In front of the leading edge.",
        "Directly above the centre of the canopy.",
        "Beneath the wing, between pilot and lower surface.",
    ],
    # aer-35: Lift-to-drag ratio depends on?
    "aer-35": [
        "…airspeed.",
        "…wing loading.",
        "…air density.",
    ],
    # aer-36: Glide ratio expresses ratio between?
    "aer-36": [
        "…wing area and wingspan.",
        "…airspeed and sink rate (horizontal vs. vertical speed).",
        "…lift and total weight in level flight.",
    ],
    # aer-37: Reducing AoA by 2° from best-glide speed?
    "aer-37": [
        "…increases the lift coefficient.",
        "…has no effect on the lift coefficient; only drag changes.",
        "…doubles the lift coefficient and halves the drag coefficient.",
    ],
    # aer-38: Continuous transition from straight to turning flight?
    "aer-38": [
        "…both wing loading and minimum flight speed decrease.",
        "…wing loading increases but minimum flight speed stays constant.",
        "…wing loading stays constant but minimum flight speed decreases.",
    ],
    # aer-39: Air density halves at?
    "aer-39": [
        "5500 m AMSL.",
        "11000 m AMSL.",
        "3050 m AMSL.",
    ],
    # aer-40: Air pressure halves at?
    "aer-40": [
        "6600 m AMSL.",
        "11000 m AMSL.",
        "3300 m AMSL.",
    ],
    # aer-41: Altitude compensation by speed — practical?
    "aer-41": [
        "Weight, wing area, etc. don't change. At altitude (higher air density) you need to run slower, with a shorter takeoff run. Downside: with higher density the wing tolerates less wind.",
        "Wing area must be reduced at altitude to maintain the same flight speed. A larger wing is needed at sea level than at high altitudes.",
        "Both wing area and pilot weight increase effectively at altitude. This is why high-altitude flights require larger reserves.",
    ],
    # aer-42: When I brake, AoA?
    "aer-42": [
        "…decreases. Speed increases and sink rate decreases. Both CL and CD decrease.",
        "…stays the same — braking only changes wing area, not AoA.",
        "…increases. Speed increases and sink rate decreases. CL drops, CD increases.",
    ],
    # aer-43: When I accelerate, AoA?
    "aer-43": [
        "…increases. I fly faster; CL and CD increase. A parachutal stall becomes possible.",
        "…stays the same — only speed and sink rate change. Both coefficients are independent of speed.",
        "…decreases. I fly slower; CL and CD increase. A spin (Vrille) becomes possible.",
    ],
    # aer-44: Where do you feel induced drag (~40%)?
    "aer-44": [
        "You feel induced drag mainly at high airspeeds, regardless of nearby gliders.",
        "Induced drag is only felt in turbulence; it's caused by wind shear, not other wings.",
        "Induced drag is felt in front of any wing, not behind. A solo glider produces more than a tandem.",
    ],
    # aer-45: More heavily loaded wing?
    "aer-45": [
        "Slower and more sluggish.",
        "Slower but with better glide ratio.",
        "Faster but less responsive to brake input.",
    ],
    # aer-46: Less heavily loaded wing?
    "aer-46": [
        "Faster and more agile.",
        "Slower but with better glide ratio.",
        "Faster but with worse glide ratio.",
    ],
    # aer-47: Payload (Zuladung) is?
    "aer-47": [
        "…everything including the wing (total flight weight).",
        "…the pilot's body weight only.",
        "…the weight of fuel and ballast carried during flight.",
    ],
    # aer-48: Wing loading is calculated from?
    "aer-48": [
        "…pilot body weight only ÷ wing area. Exclude harness, reserve, and clothing.",
        "…payload (excluding wing) ÷ projected area of the wing.",
        "…wing area ÷ total flight weight (inverse of weight density).",
    ],
    # aer-49: High glide ratio means?
    "aer-49": [
        "…a larger glide angle (steep descent — bad).",
        "…higher sink rate but better penetration in wind.",
        "…higher airspeed at trim, with worse glide angle.",
    ],
    # aer-50: If glide ANGLE is large, glide RATIO is?
    "aer-50": [
        "…large (flat descent — good).",
        "…unchanged (glide angle and glide ratio are independent).",
        "…undefined (only applies in stable trim flight).",
    ],
    # aer-51: When are you at best glide?
    "aer-51": [
        "At full speedbar (maximum airspeed).",
        "At 20–30% brake (minimum sink speed).",
        "At full brake (stall point).",
    ],
    # aer-52: Tailwind & lift — how to fly?
    "aer-52": [
        "Apply full speedbar — push hard to gain ground while wind helps.",
        "Apply full brake to stall and sink straight down into the lift core.",
        "Stay at trim speed — neither braked nor accelerated.",
    ],
    # aer-53: Headwind & sink — how to fly?
    "aer-53": [
        "Apply 50% brake to fly at minimum sink and let the wind help carry you.",
        "Stay at trim speed — neither braked nor accelerated.",
        "Apply full brake to descend rapidly and exit the sinking air.",
    ],
    # aer-54: Lateral axis (Querachse)?
    "aer-54": [
        "Roll (rollen). Stability around it = directional stability.",
        "Yaw (gieren). Stability around it = pitch stability.",
        "Pitch (nicken). Stability around it = lateral stability.",
    ],
    # aer-55: Longitudinal axis (Längsachse)?
    "aer-55": [
        "Pitch (nicken). Stability around it = directional stability.",
        "Yaw (gieren). Stability around it = roll stability.",
        "Roll (rollen). Stability around it = directional stability.",
    ],
    # aer-56: Vertical axis (Hochachse)?
    "aer-56": [
        "Pitch (nicken). Stability around it = pitch stability.",
        "Roll (rollen). Stability around it = lateral stability.",
        "Trim. Stability around it = speed stability.",
    ],
    # aer-57: Convert m/s to km/h?
    "aer-57": [
        "Divide by 3.6.",
        "Multiply by 1.85 (knots conversion).",
        "Multiply by 60.",
    ],
    # aer-58: G straight and 70° bank?
    "aer-58": [
        "Straight flight = 0 G.\n70° bank ≈ 1 G — load factor is constant in any turn.\n\nIn a turn, only airspeed changes; load factor and stall speed are unaffected by bank angle.",
        "Straight flight = 1 G.\n70° bank ≈ 2 G — load factor doubles at any banked turn.\n\nMinimum speed decreases in a turn because the wing is more efficient.",
        "Straight flight = 1 G.\n70° bank ≈ 5 G — paragliders cannot survive such bank angles.\n\nMinimum speed drops sharply, so stall risk increases.",
    ],
}
